# Generated by Django 5.0.6 on 2024-06-19 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_deactivate', 'Can deactivate mailing'), ('view_all_mailing', 'Can view all mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='data_mailing_finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 21, 9, 11, 689276, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
    ]
