# Generated by Django 5.0.6 on 2024-06-19 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='data_mailing_finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 12, 2, 50, 931948, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
    ]
